[package]
name = "rustylang"
version = "0.1.0"
authors = ["Mike Lubinets <lubinetsm@yandex.ru>"]

[dependencies]
serde_derive = "1.0.66"
toml = "0.4.6"
regex = "1.0.1"
failure = "0.1.1"
serde = "1.0.66"
serde_json = "1.0.21"
